name: Prepare Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - './idea'
      - 'README.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/**'

env:
  java: 1.8

jobs:
  prepRelease:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '${{ env.java }}'
    - uses: actions/checkout@v2
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install Bamboo SDK
      run: |
        wget -q https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
        mkdir opt
        tar -xzf *plugin-sdk* -C opt
        mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
        chmod a+x opt/atlassian-plugin-sdk/bin/*
        chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
        echo "opt/atlassian-plugin-sdk/bin" >> $GITHUB_PATH
        opt/atlassian-plugin-sdk/bin/atlas-version
    - name: Setup Git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Execute Maven Prepare Release
      run: atlas-mvn -B release:prepare
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
